update sage to 4.4.2 from upstream

diff --git a/spkg/standard/sage_scripts/sage-env b/spkg/standard/sage_scripts/sage-env
--- a/spkg/standard/sage_scripts/sage-env
+++ b/spkg/standard/sage_scripts/sage-env
@@ -2,7 +2,7 @@
 
 ###########################################################################
 #
-#  Set environment variables for building and/or running SAGE.
+#  Set environment variables for building and/or running Sage.
 #  You must source this; see below!
 # 
 #  AUTHORS:   William Stein                            2005-12
@@ -13,7 +13,7 @@
 ##########################################################################
 #
 #  If you want to set all environment variables for your shell like
-#  they are during the build of SAGE packages, type 
+#  they are during the build of Sage packages, type 
 #
 #             source local/bin/sage-env 
 #
@@ -22,47 +22,44 @@
 # 
 ##########################################################################
 
-
+# GUESS SAGE_ROOT from pwd
 SAVEDIR="`pwd`"
-
-if [ "$SAGE_ROOT" = "" ]; then
-    if [ -f sage -a -d spkg ]; then
-       SAGE_ROOT="`pwd`"
-       export SAGE_ROOT
+if [ -f sage -a -d spkg ]; then
+    GUESSED_SAGE_ROOT="`pwd`"
+else 
+    if [ -f ../../sage -a -d ../../spkg ]; then
+        cd ../../
+        GUESSED_SAGE_ROOT="`pwd`"
     else
-       if [ -f ../../sage -a -d ../../spkg ]; then
-           cd ../../
-           SAGE_ROOT="`pwd`"
-           export SAGE_ROOT
-       else
-           echo "You must set the SAGE_ROOT environment variable or"
-           echo "run this script from the SAGE_ROOT or "
-           echo "SAGE_ROOT/local/bin/ directory."
-        fi
+        GUESSED_SAGE_ROOT=""
     fi
-else
-    if [ -f sage -a -d spkg ]; then
-       if [ "$SAGE_ROOT" != "`pwd`" ]; then
-           echo "Warning: Attempted to overwrite SAGE_ROOT enviroment variable"             
-       fi
-    else
-       if [ -f ../../sage -a -d ../../spkg ]; then
-           cd ../../
-           if [ "$SAGE_ROOT" != "`pwd`" ]; then
-              echo "Warning: Attempted to overwrite SAGE_ROOT enviroment variable"             
-           fi
-       else
-           echo "You must set the SAGE_ROOT environment variable or"
-           echo "run this script from the SAGE_ROOT or "
-           echo "SAGE_ROOT/local/bin/ directory."  
-       fi
-    fi  
 fi
 cd "$SAVEDIR"
 
+
 if [ "$SAGE_ROOT" = "" ]; then
-    echo "SAGE_ROOT must be set"
-    exit 1
+    if [ "$GUESSED_SAGE_ROOT" = "" ]; then
+        echo "Error: You must set the SAGE_ROOT environment"
+        echo "variable or run this script from the SAGE_ROOT or "
+        echo "SAGE_ROOT/local/bin/ directory."
+        exit 1
+    else
+        SAGE_ROOT="$GUESSED_SAGE_ROOT"
+        export SAGE_ROOT
+    fi
+else
+    if [ -f "$SAGE_ROOT"/sage -a -d "$SAGE_ROOT"/spkg ]; then
+        # SAGE_ROOT points to a sage installation as expected
+        if [ "$SAGE_ROOT" != "$GUESSED_SAGE_ROOT" ]; then
+            echo "Warning: Attempted to overwrite SAGE_ROOT environment variable"
+        fi
+    else
+        echo "Error: The SAGE_ROOT environment variable is set to"
+        echo "a bad value. You must correct it or erase it and"
+        echo "run this script from the SAGE_ROOT or"
+        echo "SAGE_ROOT/local/bin/ directory."  
+        exit 1
+    fi
 fi
 
 
@@ -92,7 +89,7 @@ if [ 1 = 2 ]; then
     echo "if you use sh, bash or a similar shell"
 fi
 
-# Setting SAGE-related location environment variables.
+# Setting Sage-related location environment variables.
 BUILD=build
 SAGE_PACKAGES="$SAGE_ROOT/spkg" && export SAGE_PACKAGES
 SAGE_LOCAL="$SAGE_ROOT/local"   && export SAGE_LOCAL
@@ -106,9 +103,17 @@ if [ -f $SAGE_LOCAL/toolchain/toolchain-env ]; then
   source $SAGE_LOCAL/toolchain/toolchain-env
 fi
 
-# For a framework Python build on OS X, Python's bin directory is not local/bin
+# Mac OS X-specific setup
 if [ `uname` = "Darwin" ]; then
+    # For a framework Python build on OS X, Python's bin directory is not local/bin
     PATH="$SAGE_LOCAL/Frameworks/Python.framework/Versions/2.5/bin:$PATH" && export PATH
+
+    # set MACOSX_DEPLOYMENT_TARGET -- if set incorrectly, this can
+    # cause lots of random "Abort trap" issues on OSX. see trac
+    # #7095 for an example.
+    MACOSX_VERSION=`uname -r | awk -F. '{print $1}'`
+    MACOSX_DEPLOYMENT_TARGET=10.$[$MACOSX_VERSION-4]
+    export MACOSX_DEPLOYMENT_TARGET
 fi
 
 if [ "$LIBRARY_PATH" != "" ]; then
@@ -121,6 +126,8 @@ export LIBRARY_PATH
 GP_DATA_DIR="$SAGE_LOCAL/share/pari" && export GP_DATA_DIR
 GPHELP="$SAGE_LOCAL/bin/gphelp" && export GPHELP
 GPDOCDIR="$SAGE_LOCAL/share/pari/doc" && export GPDOCDIR
+
+SINGULARPATH="$SAGE_LOCAL/share/singular" && export SINGULARPATH
 
 if [ "$SAGE_SERVER" = "" ]; then
     SAGE_SERVER="http://www.sagemath.org/"
@@ -148,7 +155,7 @@ if [ -z "${SAGE_ORIG_LD_LIBRARY_PATH_SET}" ]; then
 fi
 
 if [ -z "$SAGE_TESTDIR" ]; then
-    SAGE_TESTDIR="$SAGE_ROOT"/tmp && export SAGE_TESTDIR
+    SAGE_TESTDIR="$DOT_SAGE"/tmp && export SAGE_TESTDIR
 fi
 
 LD_LIBRARY_PATH="$SAGE_ROOT/local/lib/:$LD_LIBRARY_PATH" && export LD_LIBRARY_PATH
@@ -177,9 +184,9 @@ fi
 
 ############ compilation flags
 
-# Setting SAGE-related compilation flags.
+# Setting Sage-related compilation flags.
 # This could be used in code to make special changes only when
-# code is being built as part of SAGE.
+# code is being built as part of Sage.
 __sage__="" && export __sage__
 # Set the default compiler to gcc if the enviroment variable 
 # CC is not set. 
@@ -270,13 +277,8 @@ if [ "$MAKEFLAGS" != "" ]; then
     MFLAGS="$MAKEFLAGS"  && export MFLAGS
 fi
 
-# If the language encoding isn't set, set it to be US, since
-# Sage is currently mainly a US program, and leaving this off
-# leads to some really confusing errors -- see trac #276
-
-if [ "$LANG" = "" ]; then
-    LANG="en_US.UTF-8"  && export LANG
-fi 
+# See trac 7186 -- this is needed if ecl is moved
+ECLDIR="$SAGE_LOCAL/lib/ecl/" && export ECLDIR
 
 # Export variable names. 
 export SHAREDFLAGS
@@ -291,7 +293,7 @@ echo "CC=$CC"
 echo "CFLAGS=$CFLAGS"
 echo "CXX=$CXX"
 echo "CXXFLAGS=$CXXFLAGS"
-echo "LANG=$LANG"
+echo "ECLDIR=$ECLDIR"
 echo "LD=$LD"
 echo "LDFLAGS=$LDFLAGS"
 echo "LN=$LN"
